[package]
name = "notary-tee"
version = "0.1.0-alpha.12"
edition = "2021"

[lints]
workspace = true

[features]
notary_tee = []

[dependencies]
base64 = "0.22"
bincode = "1.3"
bytes = { workspace = true }
dotenvy = "0.15"
hex = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tlsn-common = { workspace = true }
tlsn-core = { workspace = true }
tlsn-formats = { workspace = true }
tlsn-prover = { workspace = true }
notary-client = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt-multi-thread", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = "2.5"
tracing-subscriber = { workspace = true }

[lib]
path = "lib.rs"
