[package]
name = "authdecode-core"
authors = ["TLSNotary Team"]
description = "A 2PC protocol for authenticated decoding of encodings in zk"
keywords = ["tls", "mpc", "2pc"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[lib]
name = "authdecode_core"

[features]
default = []
fixtures = ["dep:rand_chacha"]
mock = ["dep:bincode", "dep:num", "dep:blake3"]
tracing = ["dep:tracing"]

[dependencies]
thiserror = "1.0.56"
rand = "0.8.5"
opaque-debug = "0.3.1"
serde =  { version = "1.0", features = ["derive"] }
lazy_static = "1.4"
itybity = "0.2"
cfg-if = "1"
enum-try-as-inner = "0.1.0"
getset = "0.1.2"

rand_chacha = { version = "0.3", optional = true}
bincode = { version = "1", optional = true}
num = { version = "0.4.1", optional = true}
blake3 = { version = "1.3.3", optional = true}
tracing = { version = "0.1", optional = true }

halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v0.3.0", default-features = false}
halo2_poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon-gadget", rev="764a682"}
group = "0.13"
ff = "0.13"

[dev-dependencies]
hex = "0.4.3"
criterion = "0.5.1"
rand_chacha = "0.3"
rand_core = "0.6"
rstest = "0.12"
bincode = "1"
blake3 = "1.3.3"
num = "0.4.1" 


